# Generated by Django 2.2.19 on 2022-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_service', '0002_auto_20220501_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Мера'),
        ),
    ]
